# ============================================================
# CivicConnect Secrets
# Values are base64-encoded.
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: civicconnect-secrets
  namespace: civicconnect
  labels:
    app: civicconnect
type: Opaque
data:
  # echo -n "civicconnect-prod-jwt-secret" | base64
  JWT_SECRET: Y2l2aWNjb25uZWN0LXByb2Qtand0LXNlY3JldA==
  # echo -n "mock-gemini-key" | base64
  GEMINI_API_KEY: bW9jay1nZW1pbmkta2V5
  # echo -n "mock-nvidia-key" | base64
  NVIDIA_API_KEY: bW9jay1udmlkaWEta2V5
  SMTP_USER: ""
  SMTP_PASS: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-uris
  namespace: civicconnect
type: Opaque
data:
  # echo -n "mongodb://mongodb:27017/citizen_db" | base64
  CITIZEN_MONGO_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvY2l0aXplbl9kYg==
  # echo -n "mongodb://mongodb:27017/issue_db" | base64
  ISSUE_MONGO_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvaXNzdWVfZGI=
  # echo -n "mongodb://mongodb:27017/assignment_db" | base64
  ASSIGNMENT_MONGO_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvYXNzaWdubWVudF9kYg==
  # echo -n "mongodb://mongodb:27017/notification_db" | base64
  NOTIFICATION_MONGO_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvbm90aWZpY2F0aW9uX2Ri
